# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_core_pb2 as ai__core__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AICoreStub:
    """================================================================
    AI Core Service — interface between Rust orchestrator and Python AI
    ================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatCompletion = channel.unary_stream(
                '/ai_core.AICore/ChatCompletion',
                request_serializer=ai__core__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=ai__core__pb2.ChatCompletionResponse.FromString,
                _registered_method=True)
        self.Completion = channel.unary_unary(
                '/ai_core.AICore/Completion',
                request_serializer=ai__core__pb2.CompletionRequest.SerializeToString,
                response_deserializer=ai__core__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.GetProviders = channel.unary_unary(
                '/ai_core.AICore/GetProviders',
                request_serializer=ai__core__pb2.GetProvidersRequest.SerializeToString,
                response_deserializer=ai__core__pb2.GetProvidersResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ai_core.AICore/Health',
                request_serializer=ai__core__pb2.HealthRequest.SerializeToString,
                response_deserializer=ai__core__pb2.HealthResponse.FromString,
                _registered_method=True)


class AICoreServicer:
    """================================================================
    AI Core Service — interface between Rust orchestrator and Python AI
    ================================================================

    """

    def ChatCompletion(self, request, context):
        """Streaming chat completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Completion(self, request, context):
        """Non-streaming completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviders(self, request, context):
        """Provider information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AICoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatCompletion,
                    request_deserializer=ai__core__pb2.ChatCompletionRequest.FromString,
                    response_serializer=ai__core__pb2.ChatCompletionResponse.SerializeToString,
            ),
            'Completion': grpc.unary_unary_rpc_method_handler(
                    servicer.Completion,
                    request_deserializer=ai__core__pb2.CompletionRequest.FromString,
                    response_serializer=ai__core__pb2.CompletionResponse.SerializeToString,
            ),
            'GetProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviders,
                    request_deserializer=ai__core__pb2.GetProvidersRequest.FromString,
                    response_serializer=ai__core__pb2.GetProvidersResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ai__core__pb2.HealthRequest.FromString,
                    response_serializer=ai__core__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_core.AICore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_core.AICore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AICore:
    """================================================================
    AI Core Service — interface between Rust orchestrator and Python AI
    ================================================================

    """

    @staticmethod
    def ChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_core.AICore/ChatCompletion',
            ai__core__pb2.ChatCompletionRequest.SerializeToString,
            ai__core__pb2.ChatCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Completion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_core.AICore/Completion',
            ai__core__pb2.CompletionRequest.SerializeToString,
            ai__core__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_core.AICore/GetProviders',
            ai__core__pb2.GetProvidersRequest.SerializeToString,
            ai__core__pb2.GetProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_core.AICore/Health',
            ai__core__pb2.HealthRequest.SerializeToString,
            ai__core__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
