// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/orchestrator.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionType int32

const (
	ExecutionType_EXECUTION_TYPE_UNSPECIFIED ExecutionType = 0
	ExecutionType_EXECUTION_TYPE_CHAT        ExecutionType = 1 // General conversation
	ExecutionType_EXECUTION_TYPE_SCAN        ExecutionType = 2 // Security scan
	ExecutionType_EXECUTION_TYPE_EXPLOIT     ExecutionType = 3 // Exploitation
	ExecutionType_EXECUTION_TYPE_BUILD       ExecutionType = 4 // Software engineering
	ExecutionType_EXECUTION_TYPE_AUDIT       ExecutionType = 5 // Smart contract audit
	ExecutionType_EXECUTION_TYPE_ANALYZE     ExecutionType = 6 // Code/binary analysis
	ExecutionType_EXECUTION_TYPE_GENERATE    ExecutionType = 7 // Payload/code generation
)

// Enum value maps for ExecutionType.
var (
	ExecutionType_name = map[int32]string{
		0: "EXECUTION_TYPE_UNSPECIFIED",
		1: "EXECUTION_TYPE_CHAT",
		2: "EXECUTION_TYPE_SCAN",
		3: "EXECUTION_TYPE_EXPLOIT",
		4: "EXECUTION_TYPE_BUILD",
		5: "EXECUTION_TYPE_AUDIT",
		6: "EXECUTION_TYPE_ANALYZE",
		7: "EXECUTION_TYPE_GENERATE",
	}
	ExecutionType_value = map[string]int32{
		"EXECUTION_TYPE_UNSPECIFIED": 0,
		"EXECUTION_TYPE_CHAT":        1,
		"EXECUTION_TYPE_SCAN":        2,
		"EXECUTION_TYPE_EXPLOIT":     3,
		"EXECUTION_TYPE_BUILD":       4,
		"EXECUTION_TYPE_AUDIT":       5,
		"EXECUTION_TYPE_ANALYZE":     6,
		"EXECUTION_TYPE_GENERATE":    7,
	}
)

func (x ExecutionType) Enum() *ExecutionType {
	p := new(ExecutionType)
	*p = x
	return p
}

func (x ExecutionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orchestrator_proto_enumTypes[0].Descriptor()
}

func (ExecutionType) Type() protoreflect.EnumType {
	return &file_proto_orchestrator_proto_enumTypes[0]
}

func (x ExecutionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionType.Descriptor instead.
func (ExecutionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

type FindingSeverity int32

const (
	FindingSeverity_FINDING_SEVERITY_UNSPECIFIED FindingSeverity = 0
	FindingSeverity_FINDING_SEVERITY_CRITICAL    FindingSeverity = 1
	FindingSeverity_FINDING_SEVERITY_HIGH        FindingSeverity = 2
	FindingSeverity_FINDING_SEVERITY_MEDIUM      FindingSeverity = 3
	FindingSeverity_FINDING_SEVERITY_LOW         FindingSeverity = 4
	FindingSeverity_FINDING_SEVERITY_INFO        FindingSeverity = 5
)

// Enum value maps for FindingSeverity.
var (
	FindingSeverity_name = map[int32]string{
		0: "FINDING_SEVERITY_UNSPECIFIED",
		1: "FINDING_SEVERITY_CRITICAL",
		2: "FINDING_SEVERITY_HIGH",
		3: "FINDING_SEVERITY_MEDIUM",
		4: "FINDING_SEVERITY_LOW",
		5: "FINDING_SEVERITY_INFO",
	}
	FindingSeverity_value = map[string]int32{
		"FINDING_SEVERITY_UNSPECIFIED": 0,
		"FINDING_SEVERITY_CRITICAL":    1,
		"FINDING_SEVERITY_HIGH":        2,
		"FINDING_SEVERITY_MEDIUM":      3,
		"FINDING_SEVERITY_LOW":         4,
		"FINDING_SEVERITY_INFO":        5,
	}
)

func (x FindingSeverity) Enum() *FindingSeverity {
	p := new(FindingSeverity)
	*p = x
	return p
}

func (x FindingSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orchestrator_proto_enumTypes[1].Descriptor()
}

func (FindingSeverity) Type() protoreflect.EnumType {
	return &file_proto_orchestrator_proto_enumTypes[1]
}

func (x FindingSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingSeverity.Descriptor instead.
func (FindingSeverity) EnumDescriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for this conversation (empty means start new)
	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// The user's message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Optional: workspace path for context
	WorkspacePath string `protobuf:"bytes,3,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	// Optional: system prompt override
	SystemPrompt string `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	// Model to use (empty = default)
	Model string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	// Additional context as key-value pairs
	Context       map[string]string `protobuf:"bytes,6,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

func (x *ChatRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunk of the response (streamed token by token or sentence by sentence)
	TextChunk string `protobuf:"bytes,1,opt,name=text_chunk,json=textChunk,proto3" json:"text_chunk,omitempty"`
	// True if this is the last message in the stream
	IsFinal bool `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// Conversation ID (returned after first message)
	ConversationId string `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// Token usage stats (only in final message)
	TokenUsage *TokenUsage `protobuf:"bytes,4,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	// Any tool calls the AI wants to make
	ToolCalls []*ToolCall `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// Error information if something went wrong
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetTextChunk() string {
	if x != nil {
		return x.TextChunk
	}
	return ""
}

func (x *ChatResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *ChatResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatResponse) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

func (x *ChatResponse) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full prompt/command to execute
	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Type of execution
	ExecutionType ExecutionType `protobuf:"varint,2,opt,name=execution_type,json=executionType,proto3,enum=orchestrator.ExecutionType" json:"execution_type,omitempty"`
	// Optional target (URL, file path, IP, etc.)
	Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// Optional: workspace path
	WorkspacePath string `protobuf:"bytes,4,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	// Optional: file contents to analyze
	FileData []byte `protobuf:"bytes,5,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	// Optional: file name for context
	FileName string `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// Model override
	Model         string `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExecuteRequest) GetExecutionType() ExecutionType {
	if x != nil {
		return x.ExecutionType
	}
	return ExecutionType_EXECUTION_TYPE_UNSPECIFIED
}

func (x *ExecuteRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ExecuteRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

func (x *ExecuteRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *ExecuteRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ExecuteRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full response text
	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Any findings discovered
	Findings []*Finding `protobuf:"bytes,2,rep,name=findings,proto3" json:"findings,omitempty"`
	// Token usage
	TokenUsage *TokenUsage `protobuf:"bytes,3,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	// Execution time in milliseconds
	ExecutionTimeMs int64 `protobuf:"varint,4,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	// Error if something went wrong
	Error string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// Whether the execution was successful
	Success       bool `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecuteResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *ExecuteResponse) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

func (x *ExecuteResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TokenUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CostUsd       float64                `protobuf:"fixed64,3,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_proto_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *TokenUsage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TokenUsage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *TokenUsage) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

type ToolCall struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ToolName       string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ParametersJson string                 `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_proto_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Severity      FindingSeverity        `protobuf:"varint,2,opt,name=severity,proto3,enum=orchestrator.FindingSeverity" json:"severity,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Target        string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Evidence      string                 `protobuf:"bytes,6,opt,name=evidence,proto3" json:"evidence,omitempty"`
	CvssScore     float64                `protobuf:"fixed64,7,opt,name=cvss_score,json=cvssScore,proto3" json:"cvss_score,omitempty"`
	Remediation   string                 `protobuf:"bytes,8,opt,name=remediation,proto3" json:"remediation,omitempty"`
	References    []string               `protobuf:"bytes,9,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_proto_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *Finding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Finding) GetSeverity() FindingSeverity {
	if x != nil {
		return x.Severity
	}
	return FindingSeverity_FINDING_SEVERITY_UNSPECIFIED
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Finding) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Finding) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *Finding) GetCvssScore() float64 {
	if x != nil {
		return x.CvssScore
	}
	return 0
}

func (x *Finding) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

func (x *Finding) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{7}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "serving", "not_serving", "degraded"
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Checks        map[string]string      `protobuf:"bytes,4,rep,name=checks,proto3" json:"checks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Component-specific health
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetChecks() map[string]string {
	if x != nil {
		return x.Checks
	}
	return nil
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{9}
}

type GetInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	BuildCommit      string                 `protobuf:"bytes,2,opt,name=build_commit,json=buildCommit,proto3" json:"build_commit,omitempty"`
	BuildDate        string                 `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	AvailableModels  []string               `protobuf:"bytes,4,rep,name=available_models,json=availableModels,proto3" json:"available_models,omitempty"`
	AvailablePlugins []string               `protobuf:"bytes,5,rep,name=available_plugins,json=availablePlugins,proto3" json:"available_plugins,omitempty"`
	MaxContextTokens int32                  `protobuf:"varint,6,opt,name=max_context_tokens,json=maxContextTokens,proto3" json:"max_context_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetBuildCommit() string {
	if x != nil {
		return x.BuildCommit
	}
	return ""
}

func (x *GetInfoResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *GetInfoResponse) GetAvailableModels() []string {
	if x != nil {
		return x.AvailableModels
	}
	return nil
}

func (x *GetInfoResponse) GetAvailablePlugins() []string {
	if x != nil {
		return x.AvailablePlugins
	}
	return nil
}

func (x *GetInfoResponse) GetMaxContextTokens() int32 {
	if x != nil {
		return x.MaxContextTokens
	}
	return 0
}

var File_proto_orchestrator_proto protoreflect.FileDescriptor

const file_proto_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x18proto/orchestrator.proto\x12\forchestrator\"\xb0\x02\n" +
	"\vChatRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eworkspace_path\x18\x03 \x01(\tR\rworkspacePath\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12@\n" +
	"\acontext\x18\x06 \x03(\v2&.orchestrator.ChatRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\fChatResponse\x12\x1d\n" +
	"\n" +
	"text_chunk\x18\x01 \x01(\tR\ttextChunk\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x129\n" +
	"\vtoken_usage\x18\x04 \x01(\v2\x18.orchestrator.TokenUsageR\n" +
	"tokenUsage\x125\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\x16.orchestrator.ToolCallR\ttoolCalls\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xfb\x01\n" +
	"\x0eExecuteRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12B\n" +
	"\x0eexecution_type\x18\x02 \x01(\x0e2\x1b.orchestrator.ExecutionTypeR\rexecutionType\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12%\n" +
	"\x0eworkspace_path\x18\x04 \x01(\tR\rworkspacePath\x12\x1b\n" +
	"\tfile_data\x18\x05 \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\"\xf3\x01\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x121\n" +
	"\bfindings\x18\x02 \x03(\v2\x15.orchestrator.FindingR\bfindings\x129\n" +
	"\vtoken_usage\x18\x03 \x01(\v2\x18.orchestrator.TokenUsageR\n" +
	"tokenUsage\x12*\n" +
	"\x11execution_time_ms\x18\x04 \x01(\x03R\x0fexecutionTimeMs\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\"o\n" +
	"\n" +
	"TokenUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12\x19\n" +
	"\bcost_usd\x18\x03 \x01(\x01R\acostUsd\"`\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\tR\x0eparametersJson\"\xa1\x02\n" +
	"\aFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x1d.orchestrator.FindingSeverityR\bseverity\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x1a\n" +
	"\bevidence\x18\x06 \x01(\tR\bevidence\x12\x1d\n" +
	"\n" +
	"cvss_score\x18\a \x01(\x01R\tcvssScore\x12 \n" +
	"\vremediation\x18\b \x01(\tR\vremediation\x12\x1e\n" +
	"\n" +
	"references\x18\t \x03(\tR\n" +
	"references\"\x14\n" +
	"\x12HealthCheckRequest\"\xf0\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12E\n" +
	"\x06checks\x18\x04 \x03(\v2-.orchestrator.HealthCheckResponse.ChecksEntryR\x06checks\x1a9\n" +
	"\vChecksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x10\n" +
	"\x0eGetInfoRequest\"\xf3\x01\n" +
	"\x0fGetInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12!\n" +
	"\fbuild_commit\x18\x02 \x01(\tR\vbuildCommit\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate\x12)\n" +
	"\x10available_models\x18\x04 \x03(\tR\x0favailableModels\x12+\n" +
	"\x11available_plugins\x18\x05 \x03(\tR\x10availablePlugins\x12,\n" +
	"\x12max_context_tokens\x18\x06 \x01(\x05R\x10maxContextTokens*\xea\x01\n" +
	"\rExecutionType\x12\x1e\n" +
	"\x1aEXECUTION_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EXECUTION_TYPE_CHAT\x10\x01\x12\x17\n" +
	"\x13EXECUTION_TYPE_SCAN\x10\x02\x12\x1a\n" +
	"\x16EXECUTION_TYPE_EXPLOIT\x10\x03\x12\x18\n" +
	"\x14EXECUTION_TYPE_BUILD\x10\x04\x12\x18\n" +
	"\x14EXECUTION_TYPE_AUDIT\x10\x05\x12\x1a\n" +
	"\x16EXECUTION_TYPE_ANALYZE\x10\x06\x12\x1b\n" +
	"\x17EXECUTION_TYPE_GENERATE\x10\a*\xbf\x01\n" +
	"\x0fFindingSeverity\x12 \n" +
	"\x1cFINDING_SEVERITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FINDING_SEVERITY_CRITICAL\x10\x01\x12\x19\n" +
	"\x15FINDING_SEVERITY_HIGH\x10\x02\x12\x1b\n" +
	"\x17FINDING_SEVERITY_MEDIUM\x10\x03\x12\x18\n" +
	"\x14FINDING_SEVERITY_LOW\x10\x04\x12\x19\n" +
	"\x15FINDING_SEVERITY_INFO\x10\x052\xb3\x02\n" +
	"\fOrchestrator\x12?\n" +
	"\x04Chat\x12\x19.orchestrator.ChatRequest\x1a\x1a.orchestrator.ChatResponse0\x01\x12F\n" +
	"\aExecute\x12\x1c.orchestrator.ExecuteRequest\x1a\x1d.orchestrator.ExecuteResponse\x12R\n" +
	"\vHealthCheck\x12 .orchestrator.HealthCheckRequest\x1a!.orchestrator.HealthCheckResponse\x12F\n" +
	"\aGetInfo\x12\x1c.orchestrator.GetInfoRequest\x1a\x1d.orchestrator.GetInfoResponseBX\n" +
	" com.shadowlynx.prox.orchestratorZ4github.com/shadowlynx/prox-cli/pkg/grpc/orchestratorb\x06proto3"

var (
	file_proto_orchestrator_proto_rawDescOnce sync.Once
	file_proto_orchestrator_proto_rawDescData []byte
)

func file_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestrator_proto_rawDesc), len(file_proto_orchestrator_proto_rawDesc)))
	})
	return file_proto_orchestrator_proto_rawDescData
}

var file_proto_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_orchestrator_proto_goTypes = []any{
	(ExecutionType)(0),          // 0: orchestrator.ExecutionType
	(FindingSeverity)(0),        // 1: orchestrator.FindingSeverity
	(*ChatRequest)(nil),         // 2: orchestrator.ChatRequest
	(*ChatResponse)(nil),        // 3: orchestrator.ChatResponse
	(*ExecuteRequest)(nil),      // 4: orchestrator.ExecuteRequest
	(*ExecuteResponse)(nil),     // 5: orchestrator.ExecuteResponse
	(*TokenUsage)(nil),          // 6: orchestrator.TokenUsage
	(*ToolCall)(nil),            // 7: orchestrator.ToolCall
	(*Finding)(nil),             // 8: orchestrator.Finding
	(*HealthCheckRequest)(nil),  // 9: orchestrator.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 10: orchestrator.HealthCheckResponse
	(*GetInfoRequest)(nil),      // 11: orchestrator.GetInfoRequest
	(*GetInfoResponse)(nil),     // 12: orchestrator.GetInfoResponse
	nil,                         // 13: orchestrator.ChatRequest.ContextEntry
	nil,                         // 14: orchestrator.HealthCheckResponse.ChecksEntry
}
var file_proto_orchestrator_proto_depIdxs = []int32{
	13, // 0: orchestrator.ChatRequest.context:type_name -> orchestrator.ChatRequest.ContextEntry
	6,  // 1: orchestrator.ChatResponse.token_usage:type_name -> orchestrator.TokenUsage
	7,  // 2: orchestrator.ChatResponse.tool_calls:type_name -> orchestrator.ToolCall
	0,  // 3: orchestrator.ExecuteRequest.execution_type:type_name -> orchestrator.ExecutionType
	8,  // 4: orchestrator.ExecuteResponse.findings:type_name -> orchestrator.Finding
	6,  // 5: orchestrator.ExecuteResponse.token_usage:type_name -> orchestrator.TokenUsage
	1,  // 6: orchestrator.Finding.severity:type_name -> orchestrator.FindingSeverity
	14, // 7: orchestrator.HealthCheckResponse.checks:type_name -> orchestrator.HealthCheckResponse.ChecksEntry
	2,  // 8: orchestrator.Orchestrator.Chat:input_type -> orchestrator.ChatRequest
	4,  // 9: orchestrator.Orchestrator.Execute:input_type -> orchestrator.ExecuteRequest
	9,  // 10: orchestrator.Orchestrator.HealthCheck:input_type -> orchestrator.HealthCheckRequest
	11, // 11: orchestrator.Orchestrator.GetInfo:input_type -> orchestrator.GetInfoRequest
	3,  // 12: orchestrator.Orchestrator.Chat:output_type -> orchestrator.ChatResponse
	5,  // 13: orchestrator.Orchestrator.Execute:output_type -> orchestrator.ExecuteResponse
	10, // 14: orchestrator.Orchestrator.HealthCheck:output_type -> orchestrator.HealthCheckResponse
	12, // 15: orchestrator.Orchestrator.GetInfo:output_type -> orchestrator.GetInfoResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_orchestrator_proto_init() }
func file_proto_orchestrator_proto_init() {
	if File_proto_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestrator_proto_rawDesc), len(file_proto_orchestrator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_proto_orchestrator_proto_depIdxs,
		EnumInfos:         file_proto_orchestrator_proto_enumTypes,
		MessageInfos:      file_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_proto_orchestrator_proto = out.File
	file_proto_orchestrator_proto_goTypes = nil
	file_proto_orchestrator_proto_depIdxs = nil
}
