// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginState int32

const (
	PluginState_PLUGIN_STATE_UNKNOWN PluginState = 0
	PluginState_PLUGIN_STATE_LOADED  PluginState = 1
	PluginState_PLUGIN_STATE_RUNNING PluginState = 2
	PluginState_PLUGIN_STATE_ERROR   PluginState = 3
	PluginState_PLUGIN_STATE_STOPPED PluginState = 4
)

// Enum value maps for PluginState.
var (
	PluginState_name = map[int32]string{
		0: "PLUGIN_STATE_UNKNOWN",
		1: "PLUGIN_STATE_LOADED",
		2: "PLUGIN_STATE_RUNNING",
		3: "PLUGIN_STATE_ERROR",
		4: "PLUGIN_STATE_STOPPED",
	}
	PluginState_value = map[string]int32{
		"PLUGIN_STATE_UNKNOWN": 0,
		"PLUGIN_STATE_LOADED":  1,
		"PLUGIN_STATE_RUNNING": 2,
		"PLUGIN_STATE_ERROR":   3,
		"PLUGIN_STATE_STOPPED": 4,
	}
)

func (x PluginState) Enum() *PluginState {
	p := new(PluginState)
	*p = x
	return p
}

func (x PluginState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginState) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginState) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x PluginState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginState.Descriptor instead.
func (PluginState) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type CapabilityLevel int32

const (
	CapabilityLevel_CAPABILITY_NONE       CapabilityLevel = 0
	CapabilityLevel_CAPABILITY_READ_ONLY  CapabilityLevel = 1
	CapabilityLevel_CAPABILITY_READ_WRITE CapabilityLevel = 2
	CapabilityLevel_CAPABILITY_FULL       CapabilityLevel = 3
)

// Enum value maps for CapabilityLevel.
var (
	CapabilityLevel_name = map[int32]string{
		0: "CAPABILITY_NONE",
		1: "CAPABILITY_READ_ONLY",
		2: "CAPABILITY_READ_WRITE",
		3: "CAPABILITY_FULL",
	}
	CapabilityLevel_value = map[string]int32{
		"CAPABILITY_NONE":       0,
		"CAPABILITY_READ_ONLY":  1,
		"CAPABILITY_READ_WRITE": 2,
		"CAPABILITY_FULL":       3,
	}
)

func (x CapabilityLevel) Enum() *CapabilityLevel {
	p := new(CapabilityLevel)
	*p = x
	return p
}

func (x CapabilityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapabilityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (CapabilityLevel) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x CapabilityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapabilityLevel.Descriptor instead.
func (CapabilityLevel) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

// A single capability a plugin requests
type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g. "network:outbound", "fs:read", "exec:shell"
	Level         CapabilityLevel        `protobuf:"varint,2,opt,name=level,proto3,enum=plugin.CapabilityLevel" json:"level,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`   // e.g. "/tmp/*", "0.0.0.0/0:443"
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // Why the plugin needs this
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetLevel() CapabilityLevel {
	if x != nil {
		return x.Level
	}
	return CapabilityLevel_CAPABILITY_NONE
}

func (x *Capability) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Capability) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Plugin manifest — bundled inside the WASM binary or alongside it
type PluginManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // Unique plugin ID, e.g. "offensive-security"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // Human-readable name
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // Semver
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Capabilities  []*Capability          `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	WasmHash      string                 `protobuf:"bytes,7,opt,name=wasm_hash,json=wasmHash,proto3" json:"wasm_hash,omitempty"`        // SHA-256 of the WASM binary for integrity
	FuelBudget    int32                  `protobuf:"varint,8,opt,name=fuel_budget,json=fuelBudget,proto3" json:"fuel_budget,omitempty"` // Max instructions (millions), 0 = unlimited
	TimeoutMs     int32                  `protobuf:"varint,9,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`    // Max execution time
	MemoryMb      int32                  `protobuf:"varint,10,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`      // Max WASM memory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginManifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginManifest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginManifest) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginManifest) GetWasmHash() string {
	if x != nil {
		return x.WasmHash
	}
	return ""
}

func (x *PluginManifest) GetFuelBudget() int32 {
	if x != nil {
		return x.FuelBudget
	}
	return 0
}

func (x *PluginManifest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *PluginManifest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

// A tool exposed by a plugin — these get registered in the AI Tool Registry
type PluginTool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // Unique tool name
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                 // What it does (for the LLM)
	JsonSchema    string                 `protobuf:"bytes,3,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"` // JSON Schema for parameters
	PluginId      string                 `protobuf:"bytes,4,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`       // Which plugin provides this tool
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginTool) Reset() {
	*x = PluginTool{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginTool) ProtoMessage() {}

func (x *PluginTool) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginTool.ProtoReflect.Descriptor instead.
func (*PluginTool) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginTool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginTool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginTool) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *PluginTool) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

// Result of a tool execution
type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // JSON string — the actual result
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`   // Error message if failed
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	FuelConsumed  int64                  `protobuf:"varint,5,opt,name=fuel_consumed,json=fuelConsumed,proto3" json:"fuel_consumed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ToolResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ToolResult) GetFuelConsumed() int64 {
	if x != nil {
		return x.FuelConsumed
	}
	return 0
}

// Request: Load a plugin from a file path or bytes
type LoadPluginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*LoadPluginRequest_FilePath
	//	*LoadPluginRequest_WasmBytes
	Source        isLoadPluginRequest_Source `protobuf_oneof:"source"`
	Manifest      *PluginManifest            `protobuf:"bytes,3,opt,name=manifest,proto3" json:"manifest,omitempty"` // Required — validated before loading
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPluginRequest) Reset() {
	*x = LoadPluginRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPluginRequest) ProtoMessage() {}

func (x *LoadPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPluginRequest.ProtoReflect.Descriptor instead.
func (*LoadPluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *LoadPluginRequest) GetSource() isLoadPluginRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *LoadPluginRequest) GetFilePath() string {
	if x != nil {
		if x, ok := x.Source.(*LoadPluginRequest_FilePath); ok {
			return x.FilePath
		}
	}
	return ""
}

func (x *LoadPluginRequest) GetWasmBytes() []byte {
	if x != nil {
		if x, ok := x.Source.(*LoadPluginRequest_WasmBytes); ok {
			return x.WasmBytes
		}
	}
	return nil
}

func (x *LoadPluginRequest) GetManifest() *PluginManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type isLoadPluginRequest_Source interface {
	isLoadPluginRequest_Source()
}

type LoadPluginRequest_FilePath struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3,oneof"` // Path to .wasm file on disk
}

type LoadPluginRequest_WasmBytes struct {
	WasmBytes []byte `protobuf:"bytes,2,opt,name=wasm_bytes,json=wasmBytes,proto3,oneof"` // Raw WASM bytes
}

func (*LoadPluginRequest_FilePath) isLoadPluginRequest_Source() {}

func (*LoadPluginRequest_WasmBytes) isLoadPluginRequest_Source() {}

type LoadPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPluginResponse) Reset() {
	*x = LoadPluginResponse{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPluginResponse) ProtoMessage() {}

func (x *LoadPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPluginResponse.ProtoReflect.Descriptor instead.
func (*LoadPluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *LoadPluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadPluginResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *LoadPluginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request: Execute a tool provided by a loaded plugin
type ExecuteToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"` // JSON string of tool arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolRequest) Reset() {
	*x = ExecuteToolRequest{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolRequest) ProtoMessage() {}

func (x *ExecuteToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolRequest.ProtoReflect.Descriptor instead.
func (*ExecuteToolRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteToolRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ExecuteToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ExecuteToolRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ExecuteToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ToolResult            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolResponse) Reset() {
	*x = ExecuteToolResponse{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolResponse) ProtoMessage() {}

func (x *ExecuteToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolResponse.ProtoReflect.Descriptor instead.
func (*ExecuteToolResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteToolResponse) GetResult() *ToolResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// List loaded plugins and their tools
type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Manifest      *PluginManifest        `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	State         PluginState            `protobuf:"varint,3,opt,name=state,proto3,enum=plugin.PluginState" json:"state,omitempty"`
	Tools         []*PluginTool          `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *PluginInfo) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginInfo) GetManifest() *PluginManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *PluginInfo) GetState() PluginState {
	if x != nil {
		return x.State
	}
	return PluginState_PLUGIN_STATE_UNKNOWN
}

func (x *PluginInfo) GetTools() []*PluginTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginInfo          `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// Get a specific plugin's info
type GetPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginRequest) Reset() {
	*x = GetPluginRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginRequest) ProtoMessage() {}

func (x *GetPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginRequest.ProtoReflect.Descriptor instead.
func (*GetPluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *GetPluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

type GetPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        *PluginInfo            `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginResponse) Reset() {
	*x = GetPluginResponse{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginResponse) ProtoMessage() {}

func (x *GetPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginResponse.ProtoReflect.Descriptor instead.
func (*GetPluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *GetPluginResponse) GetPlugin() *PluginInfo {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *GetPluginResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Unload/stop a plugin
type UnloadPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadPluginRequest) Reset() {
	*x = UnloadPluginRequest{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadPluginRequest) ProtoMessage() {}

func (x *UnloadPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadPluginRequest.ProtoReflect.Descriptor instead.
func (*UnloadPluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *UnloadPluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

type UnloadPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadPluginResponse) Reset() {
	*x = UnloadPluginResponse{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadPluginResponse) ProtoMessage() {}

func (x *UnloadPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadPluginResponse.ProtoReflect.Descriptor instead.
func (*UnloadPluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *UnloadPluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnloadPluginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Check if a WASM binary is valid and what tools it exports
type ValidatePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WasmBytes     []byte                 `protobuf:"bytes,1,opt,name=wasm_bytes,json=wasmBytes,proto3" json:"wasm_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePluginRequest) Reset() {
	*x = ValidatePluginRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePluginRequest) ProtoMessage() {}

func (x *ValidatePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePluginRequest.ProtoReflect.Descriptor instead.
func (*ValidatePluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ValidatePluginRequest) GetWasmBytes() []byte {
	if x != nil {
		return x.WasmBytes
	}
	return nil
}

type ValidatePluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Tools         []*PluginTool          `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	Manifest      *PluginManifest        `protobuf:"bytes,4,opt,name=manifest,proto3" json:"manifest,omitempty"` // Extracted from the WASM custom section
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePluginResponse) Reset() {
	*x = ValidatePluginResponse{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePluginResponse) ProtoMessage() {}

func (x *ValidatePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePluginResponse.ProtoReflect.Descriptor instead.
func (*ValidatePluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ValidatePluginResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidatePluginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ValidatePluginResponse) GetTools() []*PluginTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ValidatePluginResponse) GetManifest() *PluginManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Event emitted during plugin lifecycle
type PluginEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "loaded", "unloaded", "error", "tool_start", "tool_end"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginEvent) Reset() {
	*x = PluginEvent{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEvent) ProtoMessage() {}

func (x *PluginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEvent.ProtoReflect.Descriptor instead.
func (*PluginEvent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *PluginEvent) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PluginEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x06plugin\"}\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x05level\x18\x02 \x01(\x0e2\x17.plugin.CapabilityLevelR\x05level\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xba\x02\n" +
	"\x0ePluginManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x126\n" +
	"\fcapabilities\x18\x06 \x03(\v2\x12.plugin.CapabilityR\fcapabilities\x12\x1b\n" +
	"\twasm_hash\x18\a \x01(\tR\bwasmHash\x12\x1f\n" +
	"\vfuel_budget\x18\b \x01(\x05R\n" +
	"fuelBudget\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\t \x01(\x05R\ttimeoutMs\x12\x1b\n" +
	"\tmemory_mb\x18\n" +
	" \x01(\x05R\bmemoryMb\"\x80\x01\n" +
	"\n" +
	"PluginTool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vjson_schema\x18\x03 \x01(\tR\n" +
	"jsonSchema\x12\x1b\n" +
	"\tplugin_id\x18\x04 \x01(\tR\bpluginId\"\x9a\x01\n" +
	"\n" +
	"ToolResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12#\n" +
	"\rfuel_consumed\x18\x05 \x01(\x03R\ffuelConsumed\"\x91\x01\n" +
	"\x11LoadPluginRequest\x12\x1d\n" +
	"\tfile_path\x18\x01 \x01(\tH\x00R\bfilePath\x12\x1f\n" +
	"\n" +
	"wasm_bytes\x18\x02 \x01(\fH\x00R\twasmBytes\x122\n" +
	"\bmanifest\x18\x03 \x01(\v2\x16.plugin.PluginManifestR\bmanifestB\b\n" +
	"\x06source\"a\n" +
	"\x12LoadPluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"u\n" +
	"\x12ExecuteToolRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"A\n" +
	"\x13ExecuteToolResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.plugin.ToolResultR\x06result\"\x14\n" +
	"\x12ListPluginsRequest\"\xb2\x01\n" +
	"\n" +
	"PluginInfo\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x122\n" +
	"\bmanifest\x18\x02 \x01(\v2\x16.plugin.PluginManifestR\bmanifest\x12)\n" +
	"\x05state\x18\x03 \x01(\x0e2\x13.plugin.PluginStateR\x05state\x12(\n" +
	"\x05tools\x18\x04 \x03(\v2\x12.plugin.PluginToolR\x05tools\"C\n" +
	"\x13ListPluginsResponse\x12,\n" +
	"\aplugins\x18\x01 \x03(\v2\x12.plugin.PluginInfoR\aplugins\"/\n" +
	"\x10GetPluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\"U\n" +
	"\x11GetPluginResponse\x12*\n" +
	"\x06plugin\x18\x01 \x01(\v2\x12.plugin.PluginInfoR\x06plugin\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"2\n" +
	"\x13UnloadPluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\"F\n" +
	"\x14UnloadPluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"6\n" +
	"\x15ValidatePluginRequest\x12\x1d\n" +
	"\n" +
	"wasm_bytes\x18\x01 \x01(\fR\twasmBytes\"\xa2\x01\n" +
	"\x16ValidatePluginResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12(\n" +
	"\x05tools\x18\x03 \x03(\v2\x12.plugin.PluginToolR\x05tools\x122\n" +
	"\bmanifest\x18\x04 \x01(\v2\x16.plugin.PluginManifestR\bmanifest\"\x86\x01\n" +
	"\vPluginEvent\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs*\x8c\x01\n" +
	"\vPluginState\x12\x18\n" +
	"\x14PLUGIN_STATE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13PLUGIN_STATE_LOADED\x10\x01\x12\x18\n" +
	"\x14PLUGIN_STATE_RUNNING\x10\x02\x12\x16\n" +
	"\x12PLUGIN_STATE_ERROR\x10\x03\x12\x18\n" +
	"\x14PLUGIN_STATE_STOPPED\x10\x04*p\n" +
	"\x0fCapabilityLevel\x12\x13\n" +
	"\x0fCAPABILITY_NONE\x10\x00\x12\x18\n" +
	"\x14CAPABILITY_READ_ONLY\x10\x01\x12\x19\n" +
	"\x15CAPABILITY_READ_WRITE\x10\x02\x12\x13\n" +
	"\x0fCAPABILITY_FULL\x10\x032\x85\x04\n" +
	"\rPluginService\x12C\n" +
	"\n" +
	"LoadPlugin\x12\x19.plugin.LoadPluginRequest\x1a\x1a.plugin.LoadPluginResponse\x12F\n" +
	"\vExecuteTool\x12\x1a.plugin.ExecuteToolRequest\x1a\x1b.plugin.ExecuteToolResponse\x12F\n" +
	"\vListPlugins\x12\x1a.plugin.ListPluginsRequest\x1a\x1b.plugin.ListPluginsResponse\x12@\n" +
	"\tGetPlugin\x12\x18.plugin.GetPluginRequest\x1a\x19.plugin.GetPluginResponse\x12I\n" +
	"\fUnloadPlugin\x12\x1b.plugin.UnloadPluginRequest\x1a\x1c.plugin.UnloadPluginResponse\x12O\n" +
	"\x0eValidatePlugin\x12\x1d.plugin.ValidatePluginRequest\x1a\x1e.plugin.ValidatePluginResponse\x12A\n" +
	"\fWatchPlugins\x12\x1a.plugin.ListPluginsRequest\x1a\x13.plugin.PluginEvent0\x01b\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_plugin_proto_goTypes = []any{
	(PluginState)(0),               // 0: plugin.PluginState
	(CapabilityLevel)(0),           // 1: plugin.CapabilityLevel
	(*Capability)(nil),             // 2: plugin.Capability
	(*PluginManifest)(nil),         // 3: plugin.PluginManifest
	(*PluginTool)(nil),             // 4: plugin.PluginTool
	(*ToolResult)(nil),             // 5: plugin.ToolResult
	(*LoadPluginRequest)(nil),      // 6: plugin.LoadPluginRequest
	(*LoadPluginResponse)(nil),     // 7: plugin.LoadPluginResponse
	(*ExecuteToolRequest)(nil),     // 8: plugin.ExecuteToolRequest
	(*ExecuteToolResponse)(nil),    // 9: plugin.ExecuteToolResponse
	(*ListPluginsRequest)(nil),     // 10: plugin.ListPluginsRequest
	(*PluginInfo)(nil),             // 11: plugin.PluginInfo
	(*ListPluginsResponse)(nil),    // 12: plugin.ListPluginsResponse
	(*GetPluginRequest)(nil),       // 13: plugin.GetPluginRequest
	(*GetPluginResponse)(nil),      // 14: plugin.GetPluginResponse
	(*UnloadPluginRequest)(nil),    // 15: plugin.UnloadPluginRequest
	(*UnloadPluginResponse)(nil),   // 16: plugin.UnloadPluginResponse
	(*ValidatePluginRequest)(nil),  // 17: plugin.ValidatePluginRequest
	(*ValidatePluginResponse)(nil), // 18: plugin.ValidatePluginResponse
	(*PluginEvent)(nil),            // 19: plugin.PluginEvent
}
var file_plugin_proto_depIdxs = []int32{
	1,  // 0: plugin.Capability.level:type_name -> plugin.CapabilityLevel
	2,  // 1: plugin.PluginManifest.capabilities:type_name -> plugin.Capability
	3,  // 2: plugin.LoadPluginRequest.manifest:type_name -> plugin.PluginManifest
	5,  // 3: plugin.ExecuteToolResponse.result:type_name -> plugin.ToolResult
	3,  // 4: plugin.PluginInfo.manifest:type_name -> plugin.PluginManifest
	0,  // 5: plugin.PluginInfo.state:type_name -> plugin.PluginState
	4,  // 6: plugin.PluginInfo.tools:type_name -> plugin.PluginTool
	11, // 7: plugin.ListPluginsResponse.plugins:type_name -> plugin.PluginInfo
	11, // 8: plugin.GetPluginResponse.plugin:type_name -> plugin.PluginInfo
	4,  // 9: plugin.ValidatePluginResponse.tools:type_name -> plugin.PluginTool
	3,  // 10: plugin.ValidatePluginResponse.manifest:type_name -> plugin.PluginManifest
	6,  // 11: plugin.PluginService.LoadPlugin:input_type -> plugin.LoadPluginRequest
	8,  // 12: plugin.PluginService.ExecuteTool:input_type -> plugin.ExecuteToolRequest
	10, // 13: plugin.PluginService.ListPlugins:input_type -> plugin.ListPluginsRequest
	13, // 14: plugin.PluginService.GetPlugin:input_type -> plugin.GetPluginRequest
	15, // 15: plugin.PluginService.UnloadPlugin:input_type -> plugin.UnloadPluginRequest
	17, // 16: plugin.PluginService.ValidatePlugin:input_type -> plugin.ValidatePluginRequest
	10, // 17: plugin.PluginService.WatchPlugins:input_type -> plugin.ListPluginsRequest
	7,  // 18: plugin.PluginService.LoadPlugin:output_type -> plugin.LoadPluginResponse
	9,  // 19: plugin.PluginService.ExecuteTool:output_type -> plugin.ExecuteToolResponse
	12, // 20: plugin.PluginService.ListPlugins:output_type -> plugin.ListPluginsResponse
	14, // 21: plugin.PluginService.GetPlugin:output_type -> plugin.GetPluginResponse
	16, // 22: plugin.PluginService.UnloadPlugin:output_type -> plugin.UnloadPluginResponse
	18, // 23: plugin.PluginService.ValidatePlugin:output_type -> plugin.ValidatePluginResponse
	19, // 24: plugin.PluginService.WatchPlugins:output_type -> plugin.PluginEvent
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[4].OneofWrappers = []any{
		(*LoadPluginRequest_FilePath)(nil),
		(*LoadPluginRequest_WasmBytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
